name: rucksack
description: A collection of Utilities and Helper functions for Dart
version: 0.0.1
homepage: https://github.com/axrs/dart_rucksack
repository: https://github.com/axrs/dart_rucksack.git
issue_tracker: https://github.com/axrs/dart_rucksack/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  smart_arg:
    git:
      url: https://github.com/axrs/smart_arg.git
      ref: master
  dart_chassis_forge:
    git:
      url: https://github.com/axrs/dart_chassis_forge.git
      ref: master
  lints: ^1.0.0
  test: ^1.16.0
