version: 2.1
jobs:
  test-analyze-format-job:
    docker:
      - image: dart:stable-sdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - pub-cache-v1--{{ .Branch }}-{{ checksum "pubspec.yaml" }}
      - run: "dart pub get"
      - save_cache:
          key: pub-cache-v1--{{ .Branch }}-{{ checksum "pubspec.yaml" }}
          paths:
            - ~/.pub-cache
      - run: "bash dart_rucksack.sh --verbose test"
      - run: "bash dart_rucksack.sh --verbose lint"
      - run: "bash dart_rucksack.sh --verbose format"
      - run: "git diff-index --name-status HEAD"
workflows:
  main:
    jobs:
      - test-analyze-format-job
